[package]
name = "discord-users-list"
version = "0.1.0"
edition = "2021"

[dependencies]
envfury = "0.1"
color-eyre = "0.6"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
